#!/usr/bin/env python3

""" 
@flashforge-profile-cli

Command Line Interface to copy, modify and update flashforge profiles
"""

from flashforge_profile_cli.flashforge_profile_cli import main

if __name__ == "__main__":
    main()